# This is a registry of files that can be used as node inputs or for storing node outputs.
#
# When defining node inputs in the pipeline, reference a key from this yaml to indicate
# that the pipeline should map the file defined here to the node's input at runtime.
# Similarly, node outputs can be mapped and persisted to files defined in this yaml.
#
# Please see the Kedro Data Catalog documentation to learn more
# https://docs.kedro.org/en/stable/data/data_catalog.html

deploy_application.app_assets:
  type: datarobotx.idp.common.path_dataset.PathDataset
  filepath: include/app_${globals:frontend}

deploy_application.frontend_config:
  type: datarobotx.idp.common.path_dataset.PathDataset
  filepath: data/outputs/frontend_config.yaml

deploy_application.app_assets_with_parameters:
  type: datarobotx.idp.common.path_dataset.PathDataset
  filepath: data/outputs/app_assets_with_parameters

deploy_application.app_deploy:
  type: datarobotx.idp.common.archive_dataset.ArchiveDataset
  filepath: data/outputs/deploy.tar.gz

deploy_application.custom_application_source_id:
  type: kedro_datasets.text.TextDataset
  filepath: data/outputs/custom_application_source_id.txt

deploy_application.custom_application_source_version_id:
  type: kedro_datasets.text.TextDataset
  filepath: data/outputs/custom_application_source_version_id.txt
