# This is a registry of literal parameters that can be used as node inputs and/or node outputs.
#
# When defining node inputs in the pipeline, you can reference keys from this yaml to indicate
# that the pipeline should map the literal defined here to the node's input at runtime.
#
# Kedro precedent defines that the keys in this yaml can be referenced as below when defining
# node inputs:
# e.g. "params:my_key_1", "params:my_key_2.my_sub_key_2"

configure_deployment:
  credential_id: # Add your credential ID here. Credentials can be found at https://app.datarobot.com/account/credentials-management/
  prediction_interval: 80
  max_explanations: 10
  retraining_policy:
    name: Retrain on Accuracy Decline
    retraining_settings:
      autopilotOptions:
        blendBestModels: false
        mode: quick
        shapOnlyMode: false
        runLeakageRemovedFeatureList: true
      trigger:
        type: accuracy_decline
        schedule:
          minute:
            - 0
          hour:
            - 0
          dayOfMonth:
            - "*"
          month:
            - "*"
          dayOfWeek:
            - "*"
        statusDeclinesToWarning: true
        statusDeclinesToFailing: false
        statusStillInDecline: false
      projectOptions:
        cvMethod: RandomCV
        validationType: CV
        reps:
        validationPct:
        holdoutPct:
        metric: RMSE
      featureListStrategy: informative_features
      projectOptionsStrategy: same_as_champion
      modelSelectionStrategy: autopilot_recommended
      action: model_replacement
  batch_prediction_job_definition:
    batch_prediction_job:
      num_concurrent: 3
      intake_settings:
        type: dataset
    enabled: true
    schedule:
      minute:
        - 0
      hour:
        - 0
      dayOfMonth:
        - "*"
      month:
        - "*"
      dayOfWeek:
        - 1
    name: ${globals:project_name} Daily Batch Prediction Job
